package gnaix;

import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Set;
import java.util.stream.IntStream;

import gnaix.task.Task;
import gnaix.task.TaskList;

/**
 * Runs the Gnaix task management application.
 */
public class Gnaix {
    private static final Path FILE_PATH = Path.of("data", "gnaix.txt");

    private static final DateTimeFormatter OUTPUT_DATE_FORMAT =
            DateTimeFormatter.ofPattern("MMM dd yyyy");

    private final Ui ui;
    private final Storage storage;
    private TaskList tasks;

    /**
     * Creates a Gnaix application using the default storage file.
     */
    public Gnaix() {
        this.ui = new Ui();
        this.storage = new Storage(FILE_PATH);

        try {
            this.tasks = new TaskList(storage.load());
        } catch (IOException e) {
            this.tasks = new TaskList();
        }
    }

    /**
     * Starts the text-based Gnaix application.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        Gnaix gnaix = new Gnaix();
        gnaix.run();
    }

    /**
     * Runs the text-based Gnaix application.
     */
    private void run() {
        ui.showWelcome();

        boolean isRunning = true;

        while (isRunning) {
            ui.showLine();
            String input = ui.readCommand();
            ParsedCommand parsed = Parser.parse(input);

            if (parsed.hasError()) {
                ui.showError(parsed.getError());
                continue;
            }

            if (parsed.getCommand() == Command.BYE) {
                isRunning = false;
                continue;
            }

            ui.showMessage(executeCommand(parsed));
        }

        ui.showGoodbye();
    }

    /**
     * Executes a successfully parsed command and returns its response.
     *
     * @param parsed Parsed command to execute.
     * @return Response generated by executing the command.
     */
    private String executeCommand(ParsedCommand parsed) {
        switch (parsed.getCommand()) {
            case BYE:
                return "Bye. Hope to see you again soon!";
            case LIST:
                return getTaskListResponse();
            case TODO:
            case DEADLINE:
            case EVENT:
                assert parsed.getTask() != null
                        : "Task command should contain a parsed task";
                return addTaskAndGetResponse(parsed.getTask());
            case MARK:
                return markTaskAndGetResponse(parsed.getIndex());
            case UNMARK:
                return unmarkTaskAndGetResponse(parsed.getIndex());
            case DELETE:
                return deleteTaskAndGetResponse(parsed.getIndex());
            case DATE:
                assert parsed.getDate() != null
                        : "Date command should contain a parsed date";
                return getDateResponse(parsed.getDate());
            case FIND:
                assert parsed.getKeyword() != null
                        : "Find command should contain a parsed keyword";
                return getFindResponse(parsed.getKeyword());
            case TAG:
                assert !parsed.getTags().isEmpty()
                        : "Tag command should contain at least one tag";
                return getTagResponse(parsed.getTags());
            default:
                assert false : "Unexpected command after parsing";
                return "That's not a valid command! :(";
        }
    }

    /**
     * Saves the current task list to persistent storage.
     */
    private void save() {
        try {
            storage.save(tasks.getTasks());
        } catch (IOException e) {
            ui.showError("I couldn't save your tasks! :(");
        }
    }

    /**
     * Returns whether a one-based task index refers to an existing task.
     *
     * @param index One-based task number.
     * @return True if the index is within the current task list.
     */
    private boolean isInRange(int index) {
        return index >= 1 && index <= tasks.size();
    }

    /**
     * Processes a user command and returns the response for the GUI.
     *
     * @param input User command.
     * @return Response generated by Gnaix.
     */
    public String getResponse(String input) {
        assert tasks != null : "Task list must be initialised before processing commands";

        ParsedCommand parsed = Parser.parse(input);
        assert parsed != null : "Parser should always return a command result";

        if (parsed.hasError()) {
            return parsed.getError();
        }

        return executeCommand(parsed);
    }

    /**
     * Processes a user command and returns structured response data for the GUI.
     *
     * @param input User command.
     * @return Response containing text and optional task display data.
     */
    public GuiResponse getGuiResponse(String input) {
        assert tasks != null : "Task list must be initialised before processing commands";

        ParsedCommand parsed = Parser.parse(input);
        assert parsed != null : "Parser should always return a command result";

        if (parsed.hasError()) {
            return GuiResponse.error(parsed.getError());
        }

        return executeGuiCommand(parsed);
    }

    /**
     * Executes a command and keeps task data for GUI rendering where useful.
     *
     * @param parsed Parsed command to execute.
     * @return Structured response for the GUI.
     */
    private GuiResponse executeGuiCommand(ParsedCommand parsed) {
        switch (parsed.getCommand()) {
            case BYE:
                return GuiResponse.plain(executeCommand(parsed));
            case LIST:
                return GuiResponse.withTasks(
                        getTaskListResponse(),
                        "Here are the tasks in your list:",
                        getAllTaskDisplays(),
                        "");
            case TODO:
            case DEADLINE:
            case EVENT:
                assert parsed.getTask() != null
                        : "Task command should contain a parsed task";
                return addTaskAndGetGuiResponse(parsed.getTask());
            case MARK:
                return markTaskAndGetGuiResponse(parsed.getIndex());
            case UNMARK:
                return unmarkTaskAndGetGuiResponse(parsed.getIndex());
            case DELETE:
                return deleteTaskAndGetGuiResponse(parsed.getIndex());
            case DATE:
                assert parsed.getDate() != null
                        : "Date command should contain a parsed date";
                return getDateGuiResponse(parsed.getDate());
            case FIND:
                assert parsed.getKeyword() != null
                        : "Find command should contain a parsed keyword";
                return getFindGuiResponse(parsed.getKeyword());
            case TAG:
                assert !parsed.getTags().isEmpty()
                        : "Tag command should contain at least one tag";
                return getTagGuiResponse(parsed.getTags());
            default:
                assert false : "Unexpected command after parsing";
                return GuiResponse.error("That's not a valid command! :(");
        }
    }

    /**
     * Returns a formatted representation of the current task list.
     *
     * @return Formatted task list.
     */
    private String getTaskListResponse() {
        StringBuilder response =
                new StringBuilder("Here are the tasks in your list:");

        for (int i = 0; i < tasks.size(); i++) {
            response.append(System.lineSeparator())
                    .append(i + 1)
                    .append(". ")
                    .append(tasks.get(i));
        }

        return response.toString();
    }

    /**
     * Returns display data for all tasks in their current order.
     *
     * @return Numbered task display data.
     */
    private List<TaskDisplay> getAllTaskDisplays() {
        return IntStream.range(0, tasks.size())
                .mapToObj(index -> new TaskDisplay(index + 1, tasks.get(index)))
                .toList();
    }

    /**
     * Adds a task and returns the corresponding response.
     *
     * @param task Task to add.
     * @return Response describing the added task.
     */
    private String addTaskAndGetResponse(Task task) {
        tasks.add(task);
        save();

        return "Got it. I've added this task:"
                + System.lineSeparator()
                + "  " + task
                + System.lineSeparator()
                + "Now you have " + tasks.size() + " tasks in the list.";
    }

    /**
     * Adds a task and returns a GUI response containing the new task.
     *
     * @param task Task to add.
     * @return Structured response describing the added task.
     */
    private GuiResponse addTaskAndGetGuiResponse(Task task) {
        String text = addTaskAndGetResponse(task);

        return GuiResponse.withTasks(
                text,
                "Got it. I've added this task:",
                List.of(new TaskDisplay(tasks.size(), task)),
                "Now you have " + tasks.size() + " tasks in the list.");
    }

    /**
     * Marks a task as complete and returns the corresponding response.
     *
     * @param index One-based task number.
     * @return Response describing the result.
     */
    private String markTaskAndGetResponse(int index) {
        if (!isInRange(index)) {
            return "That task number does not exist! :(";
        }

        tasks.mark(index - 1);
        Task task = tasks.get(index - 1);
        save();

        return "Nice! I've marked this task as done:"
                + System.lineSeparator()
                + "  " + task;
    }

    /**
     * Marks a task as complete and returns task display data for the GUI.
     *
     * @param index One-based task number.
     * @return Structured response describing the result.
     */
    private GuiResponse markTaskAndGetGuiResponse(int index) {
        if (!isInRange(index)) {
            return GuiResponse.error("That task number does not exist! :(");
        }

        String text = markTaskAndGetResponse(index);

        return GuiResponse.withTasks(
                text,
                "Nice! I've marked this task as done:",
                List.of(new TaskDisplay(index, tasks.get(index - 1))),
                "");
    }

    /**
     * Marks a task as incomplete and returns the corresponding response.
     *
     * @param index One-based task number.
     * @return Response describing the result.
     */
    private String unmarkTaskAndGetResponse(int index) {
        if (!isInRange(index)) {
            return "That task number does not exist! :(";
        }

        tasks.unmark(index - 1);
        Task task = tasks.get(index - 1);
        save();

        return "OK, I've marked this task as not done yet:"
                + System.lineSeparator()
                + "  " + task;
    }

    /**
     * Marks a task as incomplete and returns task display data for the GUI.
     *
     * @param index One-based task number.
     * @return Structured response describing the result.
     */
    private GuiResponse unmarkTaskAndGetGuiResponse(int index) {
        if (!isInRange(index)) {
            return GuiResponse.error("That task number does not exist! :(");
        }

        String text = unmarkTaskAndGetResponse(index);

        return GuiResponse.withTasks(
                text,
                "OK, I've marked this task as not done yet:",
                List.of(new TaskDisplay(index, tasks.get(index - 1))),
                "");
    }

    /**
     * Deletes a task and returns the corresponding response.
     *
     * @param index One-based task number.
     * @return Response describing the deleted task.
     */
    private String deleteTaskAndGetResponse(int index) {
        if (!isInRange(index)) {
            return "That task number does not exist! :(";
        }

        Task deleted = tasks.delete(index - 1);
        save();

        return "Noted. I've removed this task:"
                + System.lineSeparator()
                + "  " + deleted
                + System.lineSeparator()
                + "Now you have " + tasks.size() + " tasks in the list.";
    }

    /**
     * Deletes a task and returns the removed task for GUI display.
     *
     * @param index One-based task number.
     * @return Structured response describing the deleted task.
     */
    private GuiResponse deleteTaskAndGetGuiResponse(int index) {
        if (!isInRange(index)) {
            return GuiResponse.error("That task number does not exist! :(");
        }

        Task deleted = tasks.get(index - 1);
        String text = deleteTaskAndGetResponse(index);

        return GuiResponse.withTasks(
                text,
                "Noted. I've removed this task:",
                List.of(new TaskDisplay(index, deleted)),
                "Now you have " + tasks.size() + " tasks in the list.");
    }

    /**
     * Returns tasks whose descriptions contain the specified keyword.
     *
     * @param keyword Keyword to search for.
     * @return Formatted matching tasks.
     */
    private String getFindResponse(String keyword) {
        StringBuilder response =
                new StringBuilder("Here are the matching tasks in your list:");

        String normalisedKeyword = keyword.toLowerCase();

        List<Integer> matchingIndices = IntStream.range(0, tasks.size())
                .filter(i -> tasks.get(i).getDescription()
                        .toLowerCase()
                        .contains(normalisedKeyword))
                .boxed()
                .toList();

        matchingIndices.forEach(index ->
                response.append(System.lineSeparator())
                        .append(index + 1)
                        .append(". ")
                        .append(tasks.get(index)));

        if (matchingIndices.isEmpty()) {
            response.append(System.lineSeparator())
                    .append("No matching tasks found :(");
        }

        return response.toString();
    }

    /**
     * Returns matching task data for a GUI find response.
     *
     * @param keyword Keyword to search for.
     * @return Structured response containing matching tasks.
     */
    private GuiResponse getFindGuiResponse(String keyword) {
        String text = getFindResponse(keyword);
        List<TaskDisplay> matchingTasks = getFindTaskDisplays(keyword);

        if (matchingTasks.isEmpty()) {
            return GuiResponse.plain(text);
        }

        return GuiResponse.withTasks(
                text,
                "Here are the matching tasks in your list:",
                matchingTasks,
                "");
    }

    /**
     * Returns tasks containing all of the specified tags.
     *
     * @param tags Tags that matching tasks must contain.
     * @return Formatted matching tasks.
     */
    private String getTagResponse(Set<String> tags) {
        StringBuilder response =
                new StringBuilder("Here are the tasks with the specified tags:");

        List<Integer> matchingIndices = IntStream.range(0, tasks.size())
                .filter(i -> tasks.get(i).getTags().containsAll(tags))
                .boxed()
                .toList();

        matchingIndices.forEach(index ->
                response.append(System.lineSeparator())
                        .append(index + 1)
                        .append(". ")
                        .append(tasks.get(index)));

        if (matchingIndices.isEmpty()) {
            response.append(System.lineSeparator())
                    .append("No tasks found with the specified tags :(");
        }

        return response.toString();
    }

    /**
     * Returns matching task data for a GUI tag-search response.
     *
     * @param tags Tags that matching tasks must contain.
     * @return Structured response containing matching tasks.
     */
    private GuiResponse getTagGuiResponse(Set<String> tags) {
        String text = getTagResponse(tags);
        List<TaskDisplay> matchingTasks = getTagTaskDisplays(tags);

        if (matchingTasks.isEmpty()) {
            return GuiResponse.plain(text);
        }

        return GuiResponse.withTasks(
                text,
                "Here are the tasks with the specified tags:",
                matchingTasks,
                "");
    }

    /**
     * Returns tasks occurring on the specified date.
     *
     * @param date Date to search.
     * @return Formatted tasks occurring on the date.
     */
    private String getDateResponse(LocalDate date) {
        StringBuilder response =
                new StringBuilder(
                        "Tasks occurring on "
                                + date.format(OUTPUT_DATE_FORMAT)
                                + ":");

        List<Task> matchingTasks = tasks.getTasks().stream()
                .filter(task -> task.occursOn(date))
                .toList();

        matchingTasks.forEach(task ->
                response.append(System.lineSeparator())
                        .append(task));

        if (matchingTasks.isEmpty()) {
            response.append(System.lineSeparator())
                    .append("No deadlines or events found on that date.");
        }

        return response.toString();
    }

    /**
     * Returns dated task data for GUI display.
     *
     * @param date Date to search.
     * @return Structured response containing tasks on the date.
     */
    private GuiResponse getDateGuiResponse(LocalDate date) {
        String text = getDateResponse(date);
        List<TaskDisplay> matchingTasks = getDateTaskDisplays(date);

        if (matchingTasks.isEmpty()) {
            return GuiResponse.plain(text);
        }

        return GuiResponse.withTasks(
                text,
                "Tasks occurring on " + date.format(OUTPUT_DATE_FORMAT) + ":",
                matchingTasks,
                "");
    }

    /**
     * Returns task displays whose descriptions contain the specified keyword.
     *
     * @param keyword Keyword to search for.
     * @return Numbered task display data for matching tasks.
     */
    private List<TaskDisplay> getFindTaskDisplays(String keyword) {
        String normalisedKeyword = keyword.toLowerCase();

        return IntStream.range(0, tasks.size())
                .filter(i -> tasks.get(i).getDescription()
                        .toLowerCase()
                        .contains(normalisedKeyword))
                .mapToObj(index -> new TaskDisplay(index + 1, tasks.get(index)))
                .toList();
    }

    /**
     * Returns task displays containing all of the specified tags.
     *
     * @param tags Tags that matching tasks must contain.
     * @return Numbered task display data for matching tasks.
     */
    private List<TaskDisplay> getTagTaskDisplays(Set<String> tags) {
        return IntStream.range(0, tasks.size())
                .filter(i -> tasks.get(i).getTags().containsAll(tags))
                .mapToObj(index -> new TaskDisplay(index + 1, tasks.get(index)))
                .toList();
    }

    /**
     * Returns task displays occurring on the specified date.
     *
     * @param date Date to search.
     * @return Numbered task display data for matching tasks.
     */
    private List<TaskDisplay> getDateTaskDisplays(LocalDate date) {
        return IntStream.range(0, tasks.size())
                .filter(i -> tasks.get(i).occursOn(date))
                .mapToObj(index -> new TaskDisplay(index + 1, tasks.get(index)))
                .toList();
    }
}
